---
language: python
python: "2.7"

before_install:

  - sudo apt-get update

install:

  - pip install ansible

script:

  # Check the role/playbook's syntax.
  - ansible-playbook -i ansible_localhost.ini 001_common_utilities.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 004_docker.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 009_ajenti.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 010_gitlab.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 011_jenkins.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 013_gogs.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 014_gogs_disable_registration.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 022_shadowsocks.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 023_haproxy.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 030_ghost.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 053_newrelic.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 059_uptime.yml --syntax-check
  - ansible-playbook -i ansible_localhost.ini 060_huginn.yml --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i ansible_localhost.ini 001_common_utilities.yml -c local --sudo
  - ansible-playbook -i ansible_localhost.ini 022_shadowsocks.yml -c local --sudo --skip-tags sysctl

  # Requests to make sure web respond.
  # - "curl --retry 3 --connect-timeout 5 --max-time 120 -s -o /dev/null http://localhost/"

notifications:
  email:
    recipients:
      - lexrus@gmail.com
    on_success: change
    on_failure: always
