---

# Update apt cache

- apt: update_cache=yes cache_valid_time=3600
  tags:
    - common
    - update

# locale-gen
- name: set default locale
  lineinfile: dest=/root/.bash_profile line='export LC_ALL="en_US.UTF-8"' state=present create=yes
  tags:
    - common
    - locale

- shell: locale-gen en_US.UTF-8
  tags:
    - common
    - locale-gen

- shell: update-locale en_US.UTF-8
  tags:
    - common
    - update-locale

# Setup hostname

- name: setup hostname
  hostname: name={{ inventory_hostname }}
  when: set_hostname
  tags:
    - common
    - hostname

# Setup default DNS

- name: setup default dns
  action: lineinfile dest=/etc/resolv.conf line="nameserver 8.8.8.8" backup=yes
  when: use_google_dns
  tags:
    - common
    - dns

# Install common packages

- name: install apt-transport-https
  apt: pkg=apt-transport-https state=installed
  tags:
    - common
    - apt-transport-https

- name: install build-essential
  action: apt pkg=build-essential state=installed
  tags:
    - common
    - build-essential

- name: install editor
  action: apt pkg={{ item }} state=installed
  with_items:
    - vim
  tags:
    - common
    - editor

- name: install common utilities
  action: apt pkg={{ item }} state=installed
  with_items:
    - git
    - mosh
    - ranger
    - htop
    - imagemagick
    - curl
  tags:
    - common
    - utilities

- name: install common python packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
    - supervisor
  tags:
    - common
    - python
    - supervisor
